# Generated by Django 4.2.7 on 2023-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('categories', models.CharField(choices=[('t-shirts', 'Tees'), ('figurines', 'Figurines'), ('posters', 'Posters')], max_length=30)),
                ('subcategories', models.CharField(choices=[('one-piece', 'OnePiece'), ('bleach', 'Bleach'), ('aot', 'AttackOnTitan'), ('baki', 'Baki'), ('jjk', 'Jujutsu Kaisen'), ('bnha', 'MHA'), ('yourname', 'YourName')], max_length=40)),
            ],
        ),
    ]
