# Generated by Django 4.2.7 on 2023-11-14 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('categories', models.CharField(choices=[('Tees', 'Tees'), ('Figurines', 'Figurines'), ('Posters', 'Posters')], max_length=30)),
                ('subcategories', models.CharField(choices=[('OnePiece', 'OnePiece'), ('Bleach', 'Bleach'), ('AttackOnTitan', 'AttackOnTitan'), ('Baki', 'Baki'), ('Jujutsu Kaisen', 'Jujutsu Kaisen'), ('MHA', 'MHA'), ('YourName', 'YourName')], max_length=40)),
                ('price', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
