# Generated by Django 4.2.7 on 2023-11-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='user',
            new_name='user_c',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.TextField(),
        ),
    ]
