# Generated by Django 4.2.7 on 2023-11-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.CharField(choices=[('Tees', 'Tees'), ('Figurines', 'Figurines'), ('Posters', 'Posters')], max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategories',
            field=models.CharField(choices=[('OnePiece', 'OnePiece'), ('Bleach', 'Bleach'), ('AttackOnTitan', 'AttackOnTitan'), ('Baki', 'Baki'), ('Jujutsu Kaisen', 'Jujutsu Kaisen'), ('MHA', 'MHA'), ('YourName', 'YourName')], max_length=40),
        ),
    ]
