# Generated by Django 4.2.7 on 2023-11-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_user_cartitems_user_c_alter_cartitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='user_c',
            field=models.TextField(),
        ),
    ]
