# Generated by Django 4.2.7 on 2023-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appusermanager_is_active_appusermanager_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusermanager',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
